apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: <your-docker-registry>/result:latest
          command: ["nodemon"]  # Optional: Only if overriding Dockerfile ENTRYPOINT
          args: ["server.js"]   # Optional: Only if overriding Dockerfile CMD
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: POSTGRES_HOST
              value: "db"

---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001  # Expose on port 30001
  selector:
    app: result