apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: <your-docker-registry>/worker:latest  # Replace with your image
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: POSTGRES_HOST
              value: "db"